version: '3'

services:
  
  model-service:
    image: ghcr.io/remla2024-team14/model-service:latest
    # build: ./model-service
    # The volumes mapping ensures that changes to your application code are reflected in real-time within the container.
    volumes:
      - ./model-service:/usr/src/app
    ports:
      - "4000:5000"
  
  app: 
    image: ghcr.io/remla2024-team14/app:latest 
    # build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:8000"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000/predict
    depends_on:
      - model-service
