version: '3'

services:
  
  model-service:
    image: ghcr.io/remla2024-team14/model-service:latest
    ports:
      - "4000:5000"
  
  app:
    image: ghcr.io/remla2024-team14/app:latest
    ports:
      - "3001:8000"
    environment:
      - MODEL_SERVICE_URL=http://model-service:5000/predict
    depends_on:
      - model-service
