version: '3'

services:
  
  model-service: 
    image: python:3.12-slim-bookworm
    # build: ./model-service
    # The volumes mapping ensures that changes to your application code are reflected in real-time within the container.
    volumes:
      - ./model-service:/usr/src/app
    ports:
      - "8080:5000"
  
  app: 
    image: python:3.12-slim-bookworm
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:8000"
    environment:
      - MODEL_SERVICE_URL=http://0.0.0.0:5000/predict
    depends_on:
      - model-service
