---
- hosts: controller
  tasks:
    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Add Helm repos
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Kubernetes Dashboard
      shell: |
        helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
        helm repo update
        helm install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --namespace kube-system --create-namespace

    - name: Install Prometheus
      shell: |
        helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace

    - name: Install Grafana
      shell: |
        helm install grafana grafana/grafana --namespace monitoring

    - name: Create NodePort service for Grafana
      shell: |
        kubectl expose deployment grafana --type=NodePort --name=grafana-service --namespace monitoring

    - name: Create NodePort service for Prometheus
      shell: |
        kubectl expose deployment prometheus-server --type=NodePort --name=prometheus-service --namespace monitoring
